import re

from f import color
from reques import get_url_with_retry
from yt_api import info_from_video_id


def convert_time_to_seconds(time):
    h, m, s = time.split(":")
    return int(h) * 3600 + int(m) * 60 + float(s)


def convert_overlapping_words_to_non_overlapping_words(words):
    """
    Converts overlapping words to non overlapping words
    """

    for i in range(len(words)):

        if i == len(words) - 1:
            break

        if words[i]["end"] > words[i + 1]["start"]:

            words[i]["end"] = words[i + 1]["start"]

    return words


def parse_xml_to_subtitles(xml):
    """
    Parse the xml and return a list of Subtitle objects
    """
    # Get the list of subtitles
    subtitles = re.findall(r'<p begin="(.+?)" end="(.+?)".*?>(.+?)</p>', xml, re.DOTALL)
    words = []

    for subtitle in subtitles:
        text = subtitle[2]
        start = subtitle[0]
        end = subtitle[1]

        text = re.sub(r"<br />", " ", text)  # this is for the break tags

        text = re.sub(r"&#39;", "'", text)  # this is for the apostrophe
        text = re.sub(r"&quot;", '"', text)  # this is for the double quotes
        text = re.sub(r"&amp;", "&", text)  # this is for the ampersand
        text = re.sub(r"&lt;", "<", text)  # this is for the less than sign
        text = re.sub(r"&gt;", ">", text)  # this is for the greater than sign

        # <p begin="00:09:25.260" end="00:09:30.299" style="s2">here</p>

        # Convert the start time to seconds
        start = convert_time_to_seconds(start)
        end = convert_time_to_seconds(end)

        words.append({"text": text, "start": start, "end": end})

    return words


def get_words_from_piped_url(url):

    response = get_url_with_retry(url)
    words = parse_xml_to_subtitles(response.text)
    words = [word for word in words if word["text"]]

    return convert_overlapping_words_to_non_overlapping_words(words)


def get_syllable_count(word: str) -> int:
    word: str = word.lower()
    if not word:
        return 0
    count: int = 0
    vowels: str = "aeiouy"
    if word[0] in vowels:
        count += 1
    for index in range(1, len(word)):
        if word[index] in vowels and word[index - 1] not in vowels:
            count += 1
    if word.endswith("e"):
        count -= 1
    if word.endswith("le"):
        count += 1
    if count == 0:
        count += 1

    return count


def divide_the_text_by_space_with_syllables(words):

    new_words = []
    for word in words:
        text = word["text"]
        start = word["start"]
        end = word["end"]

        # strip the text
        text = text.strip()

        text = text.split(" ")
        number_of_words = len(text)

        syllables_count = [get_syllable_count(text[i]) for i in range(number_of_words)]

        total_syllables = sum(syllables_count)

        time_per_syllable = (end - start) / total_syllables

        for i in range(number_of_words):
            text_to_add = text[i]
            start_time = start if i == 0 else new_words[-1]["end"]
            end_time = start_time + (syllables_count[i] * time_per_syllable)

            # convert the start and end time to 3 decimal places
            start_time = round(start_time, 3)
            end_time = round(end_time, 3)

            new_words.append(
                {"text": text_to_add, "start": start_time, "end": end_time}
            )

    return new_words


def divide_the_text_by_space_without_syllables(words):
    """
    It takes a list of words, and for each word, it splits the text by space,
    and then adds the start
    and end time of the word
    :param words: the list of words that we want to divide by space
    :return: A list of dictionaries.
    """
    new_words = []
    for word in words:
        text = word["text"]
        start = word["start"]
        end = word["end"]
        text = text.split(" ")
        number_of_words = len(text)
        time_per_word = (end - start) / number_of_words
        new_words.extend(
            {
                "text": text[i],
                "start": start + time_per_word * i,
                "end": start + time_per_word * (i + 1),
            }
            for i in range(number_of_words)
        )

    return new_words


def divide_the_text_by_space(words):
    """
    It takes a list of words, and for each word, it splits the text by space,
    and then adds the start
    and end time of the word

    :param words: the list of words that we want to divide by space
    :return: A list of dictionaries.
    """

    try:
        return divide_the_text_by_space_with_syllables(words)
    except Exception as error:  # pylint: disable=broad-except
        print(f"{color.RED}Error: {error} in the word {words}{color.END}")

        return divide_the_text_by_space_without_syllables(words)


def get_words_from_video_info(video_info):

    subtitles = video_info["subtitles"]

    words, is_generated = [], False

    subtitles.sort(key=lambda x: x["autoGenerated"], reverse=True)

    try:
        for subtitle in subtitles:
            if "English" in subtitle["name"] or "en" in subtitle["name"]:
                words = get_words_from_piped_url(subtitle["url"])
                is_generated = subtitle["autoGenerated"]

                if words:
                    break

    except Exception as error:  # pylint: disable=broad-except
        print(error)

    return words, is_generated


def get_words_and_is_generated_from_video_info_or_video_id(
    video_info=None, video_id=None
):

    if video_info is None and video_id is None:
        raise ValueError("video_info and video_id cannot be None at the same time")

    if video_info is None:
        video_info = info_from_video_id(video_id)
    if video_info is None:
        return None, None

    words, is_generated = get_words_from_video_info(video_info)

    return words, is_generated


def remove_words_with_no_text(words):
    return [word for word in words if word["text"]]


def remove_square_brackets(words):
    """
    It removes the words that are between square brackets
    :param words: the list of words
    :return: the list of words without the words that are between square brackets
    """
    return [
        word
        for word in words
        if not word["text"].startswith("[") and not word["text"].endswith("]")
    ]


def remove_foreign(words):
    """
    It removes the word foreign if it is in first 60 seconds or last 60 seconds
    :param words: the list of words
    :return: the list of words without the word foreign
    """

    for word in words:
        if word["text"] == "foreign" and (
            word["start"] < 60 or word["end"] > (words[-1]["end"] - 60)
        ):
            words.remove(word)

    return words


PROFANITY_RAW = "[ __ ]"  # How YouTube transcribes profanity
PROFANITY_CONVERTED = "*****"  # Safer version for tokenizing


def remove_unnecessary_words(words):
    """
    It removes the unnecessary words from the list of words
    :param words: the list of words
    :return: the list of words without the unnecessary words
    """

    for word in words:

        text = word["text"]

        # Remove zero-width spaces and strip trailing and leading whitespace
        text = (
            text.replace("\u200b", "")
            .replace("\u200c", "")
            .replace("\u200d", "")
            .replace("\ufeff", "")
            .strip()
        )
        text = text.replace("\n", " ").replace("\t", " ").replace("\r", " ")
        text = text.replace("\u2028", " ").replace("\u2029", " ")
        text = text.replace(PROFANITY_RAW, PROFANITY_CONVERTED)

        if text != word["text"]:
            word["text"] = text

    # remove the words with no text
    words = remove_words_with_no_text(words)

    words = divide_the_text_by_space(words)

    # remove the words with no text
    words = remove_words_with_no_text(words)

    # remove the words that are between square brackets
    words = remove_square_brackets(words)

    # remove the word foreign if it is in first 60 seconds or last 60 seconds
    words = remove_foreign(words)

    return words


if __name__ == "__main__":
    video_id = "Q_xojS5LRRA"

    words, _ = get_words_and_is_generated_from_video_info_or_video_id(video_id=video_id)

    words = convert_overlapping_words_to_non_overlapping_words(words)

    words = divide_the_text_by_space(words)

    words = remove_square_brackets(words)

    words = remove_foreign(words)

    print(words)
